# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        additional_dependencies: ['click<8.1']

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: v0.3.3
    hooks:
      - id: pep257

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
      - id: autopep8

default_language_version:
  python: python3.7
